application: feedstreams
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin
    
# Bot mappings go below here

# - url: /samplebot
#   script: samplebot.py

- url: /admin/.*
  script: feedadmin.py
  login: admin

- url: /feedpoller/.*
  script: feedpoller.py
  login: admin

- url: /subscriber/.*
  script: subscriber.py

- url: /feeds
  script: feedbot.py

- url: /feeds/.*
  script: feedbot.py


# catchall handler

- url: .*
  script: main.py
